### ISSUE TITLE
Using in psychopy

### ISSUE THREAD

**Issue by legg0028** [olivettigroup/article-downloader#2]
I'm trying to use articledownloader through psychopy but this line of code: 
`from articledownloader.articledownloader import ArticleDownloader`
produces this error:
`File"C:\Users\legg0028\Dropbox\flinders_university\owen_R_classes\download_journal\0.1_article_downlod\articledownloader\articledownloader.py", line 5, in <module>from autologging import logged, traced ImportError: No module named autologging`

Is this because I have not imported the requirements (require, etc.)? If so, do you know how I can import these through psychopy?

**Comment by eddotman** [comment]
If you try `pip install -r requirements.txt` from the root folder of the repository, that should work.

Alternatively, you can just install the latest requirements by default (since the txt file might be a bit out of date...):

`pip install requests autologging htmlparser` 

Let me know if that works!
